/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pollutrack;

import static com.mycompany.pollutrack.ModifUser.user;
import static com.mycompany.pollutrack.Register.isNumeric;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmad
 */
public class EditingData extends javax.swing.JFrame {
    boolean isT=false;
    String ubahapa="";
    String isiUbah="";
    /**
     * Creates new form EditingData
     */
    public EditingData() {
        initComponents();
        indeks2.setText(TambahPencemaran.user);
         setLocationRelativeTo(null);
        if(!TambahPencemaran.pencemaran.equals("tanah"))
            isT=true;
        istanah.setVisible(isT);
        if(TambahPencemaran.pencemaran.equals("tanah"))
            indeks1.setText("Tingkat Pencemaran Tanah:");
        if(TambahPencemaran.pencemaran.equals("air"))
            indeks1.setText("Indeks Pencemar:");
        
        if(TambahPencemaran.pencemaran.equals("udara"))
            indeks1.setText("ISPU:");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        istanah = new javax.swing.JPanel();
        parammasuk = new javax.swing.JTextField();
        parameterkritis = new javax.swing.JLabel();
        indeksmasuk = new javax.swing.JTextField();
        indeks = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        indeks1 = new javax.swing.JLabel();
        indeks2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parameterkritis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        parameterkritis.setText("Parameter Kritis:");

        javax.swing.GroupLayout istanahLayout = new javax.swing.GroupLayout(istanah);
        istanah.setLayout(istanahLayout);
        istanahLayout.setHorizontalGroup(
            istanahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, istanahLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(istanahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(parameterkritis, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(parammasuk)))
        );
        istanahLayout.setVerticalGroup(
            istanahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(istanahLayout.createSequentialGroup()
                .addComponent(parameterkritis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parammasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        indeks.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        indeks.setText("Kosongkan Jika Data Tetap");

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        indeks1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        indeks1.setText("jLabel1");

        indeks2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        indeks2.setText("Kosongkan Jika Data Tetap");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(indeksmasuk)
                        .addComponent(indeks, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(indeks1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(indeks2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                    .addComponent(istanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(indeks)
                .addGap(17, 17, 17)
                .addComponent(indeks2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indeks1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indeksmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(istanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(TambahPencemaran.pencemaran.equals("udara")){
            if(parammasuk.getText().trim().equals("")){}
            else{ubahapa="Parameter_kritis";isiUbah=parammasuk.getText();ubah(); }
            if(indeksmasuk.getText().trim().equals("")){}
            else{
                if(isNumeric(indeksmasuk.getText())){ubahapa="ISPU";isiUbah=indeksmasuk.getText();ubah(); }
                else JOptionPane.showMessageDialog(this, "ISPU Harus Angka");}
            JOptionPane.showMessageDialog(this, "Ubah Data Berhasil");
            this.dispose();
            TambahPencemaran.fetchtable(TambahPencemaran.pencemaran);
            
            return;
        }
        if(TambahPencemaran.pencemaran.equals("air")){
            if(parammasuk.getText().trim().equals("")){}
            else{ubahapa="Parameter_kritis";isiUbah=parammasuk.getText();ubah(); }
            if(indeksmasuk.getText().trim().equals("")){}
            else{
                if(isNumeric(indeksmasuk.getText())){ubahapa="Nilai_IP";isiUbah=indeksmasuk.getText();ubah(); }
                else JOptionPane.showMessageDialog(this, "Nilai IP Harus Angka");}
            JOptionPane.showMessageDialog(this, "Ubah Data Berhasil");
            this.dispose();
            TambahPencemaran.fetchtable(TambahPencemaran.pencemaran);
            return;
        }
        if(TambahPencemaran.pencemaran.equals("tanah")){
            if(indeksmasuk.getText().trim().equals("")){}
            else{
                if(isNumeric(indeksmasuk.getText())){ubahapa="Tingkat_pencemaran_tanah";isiUbah=indeksmasuk.getText();ubah(); }
                else JOptionPane.showMessageDialog(this, "Nilai Pecemaran Tanah Harus Angka");}
            JOptionPane.showMessageDialog(this, "Ubah Data Berhasil");
            this.dispose();
            TambahPencemaran.fetchtable(TambahPencemaran.pencemaran);
           
        }
        
        
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    void ubah(){
        String jdbcURL = "jdbc:sqlserver://localhost:1433;databaseName=BDKEL6;encrypt=true;trustServerCertificate=true;";
        String usernameDB = "sa";
        String passwordDB = "fafa12345";
         
         try (Connection connection = DriverManager.getConnection(jdbcURL, usernameDB, passwordDB);
             PreparedStatement statement = connection.prepareStatement(String.format("Update Pencemaran_%s Set %s='%s'WHERE ID_LOKASI=(SELECT ID_LOKASI FROM LOKASI WHERE NAMA_LOKASI='%s')",TambahPencemaran.pencemaran,ubahapa,isiUbah,TambahPencemaran.user))){
          
           statement.executeUpdate();
           
            
           
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred: " + ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel indeks;
    private javax.swing.JLabel indeks1;
    private javax.swing.JLabel indeks2;
    private javax.swing.JTextField indeksmasuk;
    private javax.swing.JPanel istanah;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel parameterkritis;
    private javax.swing.JTextField parammasuk;
    // End of variables declaration//GEN-END:variables
}
